### ISSUE TITLE
[fearure request] keep screen on while the app is open

### ISSUE THREAD

**Issue by gbdomubpkm** [patrickjane/ut-plants#11]
Hello.
Thank you for your great and very efficient app.
would it be possible to have this option like in music-app?
![screenshot20220924_151511167](https://user-images.githubusercontent.com/50362604/192100669-686ebcde-dfe8-4ad9-813f-af3dc6c083d9.png)

**Comment by patrickjane** [comment]
Normally, the screen should be controlled by operating system settings (e.g. turn off screen after XY minutes of inactivity). For some apps, it makes sense to overrule this setting; e.g. for navigation apps.

I don't think that forcing screen on for normal apps is a common design pattern on ubuntu touch, and I am a bit unsure why this would be useful. The plant app is not an app which does something over time, while you are not handling your phone. Instead, when you use the app, you probably have the phone in your hands and you're touching the screen.

In which scenario did you end up with the screen going dark while you wanted to use the app?

**Comment by gbdomubpkm** [comment]
Hello. Personally, I have a screen lock system setting after 2 minutes that I can of course change. In my practice of the plant app, it bothers me a little to have this app lock up too quickly when I take several photos spaced out in time that I identify within a reasonable time. Or should it be the screen that does not lock when taking spaced in time photos, which will also leave the screen on when using the plant app ?

**Comment by patrickjane** [comment]
What do you mean with "spaced out in time photos"?

**Comment by gbdomubpkm** [comment]
I am simply talking about taking photos spaced several minutes apart.

**Comment by patrickjane** [comment]
Gonna investigate a possible solution.

**Comment by gbdomubpkm** [comment]
> Gonna investigate a possible solution.

Thank you

**Comment by patrickjane** [comment]
Implemented with version 1.3.0. / [2d8c871](https://github.com/patrickjane/ut-plants/commit/2d8c87167a556806b4a61b5246c8875e77be5bf8).

**Comment by gbdomubpkm** [comment]
> Implemented with version 1.3.0. / [2d8c871](https://github.com/patrickjane/ut-plants/commit/2d8c87167a556806b4a61b5246c8875e77be5bf8).

Thanks a lot. 👍. I think this mechanism will please. Maybe you should specify on the OpenStore that the plant app needs to be restarted after setting the switch to ON for the mechanism to work. Anyway, that's how it is on my Volla.
