### ISSUE TITLE
[feature request] additional plant info

### ISSUE THREAD

**Issue by gbdomubpkm** [patrickjane/ut-plants#12]
Would it be possible to get a display of additional plant information?
Particularly mentioning if a plant is dangerous or not and the dangerous parts of the identified plants seems to me very interesting and useful information.

**Comment by patrickjane** [comment]
Sure, it would be possible to display additional information in the app.

**However**, all information about a plant is coming from the web-service offered by Pl@ntNet.org, therefore I am bound to use/display whatever this service is offering.
Currently, as I see it, the service does not offer the kind of information you requested. You are free to submit this request to Pl@ntNet.org, maybe they would introduce the feature on their side. In case they do, I can add it to the app.

**Comment by gbdomubpkm** [comment]
I will surely ask them. Quite surprised they don't provide this basic usefull info.
