### ISSUE TITLE
UI elements

### ISSUE THREAD

**Issue by cibersheep** [patrickjane/ut-plants#15]
Some UI elements could follow OS [HIG](https://docs.ubports.com/en/latest/humanguide/)
- Edit and delete buttons can be used as [leading](https://api-docs.ubports.com/sdk/apps/qml/Ubuntu.Components/ListItem.html#sdk-ubuntu-components-listitem-leadingactions) and trailing actions of the ListItem
- The select plant part Dialog misses the Title, the current element selected, the text of each option is centered (instead of aligned to the left) and the main button says "Okay" which could be better saying «Select»

:)

**Comment by patrickjane** [comment]
I have updated the app for the Okay->Select change ([1a4bee1](https://github.com/patrickjane/ut-plants/commit/1a4bee13a98958f7b0238d46431b3192745defae)).
For the list, I am not using `ListItem`, therefore no leading and trailing actions are available. It would be a bigger refactoring to use `ListItem`, so for now this is gonna stay as it is.
