### ISSUE TITLE
api input field hidden by keyboard

### ISSUE THREAD

**Issue by Danfro** [patrickjane/ut-plants#6]
The OSK does hide the API key input field. Not good for manual input. Device Xperia X.

![grafik](https://user-images.githubusercontent.com/37637312/179085425-3dbd7a55-a5e1-4e8e-a458-901ef4912ce9.png)

**Comment by Danfro** [comment]
A, you already released the fix. Good. I can confirm this is fixed. So lets close this issue. Thanks for the work.

**Comment by patrickjane** [comment]
Thanks for your help!
