### ISSUE TITLE
feature request: also show common name in list on main page

### ISSUE THREAD

**Issue by Danfro** [patrickjane/ut-plants#8]
At least I know only very few latin plant names. So it would be much more convenient to have the common name listed on the main page in the list view as well.

**Comment by patrickjane** [comment]
Done with [5b6c733](https://github.com/patrickjane/ut-plants/commit/5b6c7336d7139b1e8d20989e11922b622b99bb5c)

**Comment by Danfro** [comment]
Thanks a lot for the quick implementation. :+1:
